### ISSUE TITLE
کانفیگ کردن پروژه

### ISSUE THREAD

**Issue by aliidont** [iFaridreza/Free_Internet#1]
سلام من فایل Config.json رو چطوری ایجاد کنم؟

**Comment by iFaridreza** [comment]
درود وقتت بخیر.
نیازی نیست شما ایجاد کنی کافیه یک بار ران کنی خودش ایجاد میکنه ، و تکمیلش کنی❤️

**Comment by aliidont** [comment]
ممنون⭐
